### ISSUE TITLE
[Bug]: Task :braze_react-native-sdk:generateCodegenSchemaFromJavaScript FAILED running on Android

### ISSUE THREAD

**Issue by cprus** [braze-inc/braze-react-native-sdk#285]
### Which Platforms?

Android

### Which React Native Version?

0.76.6

### Which @braze/react-native-sdk SDK version?

13.1.1

### Repro Rate

100% of the time

### Steps To Reproduce

Try to run the app on the Android emulator i.e. npx react-native run-android

### Expected Behavior

App should build and run on Android emulator.

### Actual Incorrect Behavior

App is unable to build and run on the Android emulator due to the error thrown.

### Verbose Logs

```shell
> Task :braze_react-native-sdk:generateCodegenSchemaFromJavaScript FAILED

node:fs:1634
  const stats = binding.lstat(
                        ^

Error: ENOENT: no such file or directory, lstat 'android'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':braze_react-native-sdk:generateCodegenSchemaFromJavaScript'.
```

### Additional Information

In the process of trying to upgrade React Native from 0.75.4 to 0.76.6. Haven't had this issue until after I did the React native upgrade. Seems to run fine on iOS.

**Comment by vanessaland** [comment]
Hi @cprus ,

Thanks for raising this! We are currently working on updating our SDK to support up to React Native 0.77, which should fix this issue. 

I'll keep you posted on our upcoming release in this thread. Thank you!

**Comment by vanessaland** [comment]
Hi @cprus ,

We just released React Native SDK [13.2.0](https://github.com/braze-inc/braze-react-native-sdk/releases/tag/13.2.0) which adds compatibility with React Native 0.77. 

I'll close this issue for now, but if you are still experiencing this issue, feel free to re-open or reach out to our support team at [support@braze.com](mailto:support@braze.com).

Thank you!

**Comment by cprus** [comment]
Hi @vanessaland,

Thanks for the quick response. I have just tried updating to 13.2.0 but am still running into the same issue when I enable the new react native architecture for android in the gradle.properties file. If I set it to false "newArchEnabled=false" then it works correctly, so something still isn't playing nice with the new architecture it seems.
